[app]
## Log directory  (default: ~\AppData\Local\restic-replica)
# log_directory = 'C:\restic-replica\logs'


[restic]
## path to the restic binary to use  (default: restic.exe)
# path = 'C:\restic.exe'

[restic.environment]
## environment variables common to all restic commmands
## WARNING: environment variables set here will overwrite any set on a per-repository basis.
# RESTIC_PROGRESS_FPS = '0.003333'


[policy]
## Snapshot filtering options used by the copy command
## If none of the "keep-*" options below are set/uncommented, all snapshots will be copied.
# keep-last = 24
# keep-daily = 30
# keep-weekly = 8
# keep-monthly = 6
# keep-yearly = 2
# exclude-current-period = false


[source]
## Location of the source restic repository, where snapshots will be copied *from*. 
## This needs to be initialised in advance, but supports all of the restic repository types detailed here:
## https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
repository_uri = 'C:\backups\restic_repo'

## repository password.
password = 'secret'

## location of password file. 
## Note: this option overrides the "password" option, and is incompatible with "password_command".
# password_file = 'C:\path\to\password_file'

## command printing the password for the repository to stdout.
## Note: this option overrides the "password" option, and is incompatible with "password_file".
# password_command = 'C:\path\to\password_command'

[source.environment]
## environment variables specific to the source repository
## Note: will be combined with destination.environment during copy operation
# RESTIC_COMPRESSION = 'max'


[destination]
## Location of the destination restic repository, where snapshots will be copied *to*. 
## This needs to be initialised in advance, and for optimal deduplication results should use the same chunker parameters as the source repository:
## https://restic.readthedocs.io/en/stable/045_working_with_repos.html?highlight=copy#ensuring-deduplication-for-copied-snapshots

## WARNING: If authentication to this repository requires the setting of environment variables (e.g. AWS_ACCESS_KEY_ID),
##   these will apply to *both* repositories during the copy operation. This is a restic limitation. Notable exceptions to 
##   this are "RESTIC_PASSWORD", "RESTIC_PASSWORD_FILE", and "RESTIC_PASSWORD_COMMAND".
##   You can avoid  this limitation by using the rclone backend for one repository, along with remotes which are configured in rclone.
##   https://restic.readthedocs.io/en/stable/045_working_with_repos.html#copying-snapshots-between-repositories 
repository_uri = 'C:\offsite-backups\restic_repo'

## repository password.
password = 'secret'

## location of password file. 
## Note: this option overrides the "password" option, and is incompatible with "password_command".
# password_file = 'C:\path\to\password_file'

## command printing the password for the repository to stdout.
## Note: this option overrides the "password" option, and is incompatible with "password_file".
# password_command = 'C:\path\to\password_command'


[destination.environment]
## environment variables specific to the destination repository
## Note: will be combined with destination.environment during copy operation
# RESTIC_COMPRESSION = 'max'